<!-- Generated by AI (Claude) -->
<!-- this is not directly related to progeraming for the web and it is just like a headace with ble so i choce to get ai to genarate -->
<!-- if you would like i am happy to rewrite if i need to -->
<template>
  <ion-header>
    <ion-toolbar>
      <ion-buttons slot="start" v-if="form.id">
        <ion-button color="danger" @click="del">Delete</ion-button>
      </ion-buttons>
      <ion-title>{{ form.id ? 'Edit car' : 'Add car' }}</ion-title>
      <ion-buttons slot="end">
        <ion-button @click="dismiss('cancel')">Cancel</ion-button>
      </ion-buttons>
    </ion-toolbar>
  </ion-header>

  <ion-content class="ion-padding">
    <ion-input
      v-model="form.nickname"
      label="Car nickname"
      label-placement="stacked"
      fill="outline"
      placeholder="e.g. Mum's Corolla"
      class="form-field"
    />
    <ion-input
      v-model="form.plate"
      label="Licence plate"
      label-placement="stacked"
      fill="outline"
      placeholder="e.g. ABC 123"
      autocapitalize="characters"
      class="form-field plate-field"
    />
    <ion-item lines="none">
      <ion-checkbox v-model="noPlates" slot="start"></ion-checkbox>
      <ion-label>I don't have my Flip Plates yet</ion-label>
    </ion-item>
    <p v-if="noPlates" class="no-plates-hint">
      You can buy Flip Plates at <a href="https://example.com" target="_blank" rel="noopener">example.com</a>.
    </p>

    <!-- everything below is L-plate hardware setup; hidden when the user says
         they don't have their plates yet -->
    <template v-if="!noPlates">
    <ion-input
      v-model="form.ble_device_name"
      label="Device"
      label-placement="stacked"
      fill="outline"
      class="form-field"
      readonly
    />

    <ion-button expand="block" fill="outline" @click="scan" :disabled="scanning">
      {{ scanning ? 'Scanning…' : 'Scan for Bluetooth devices' }}
    </ion-button>

    <ion-list v-if="visibleDevices.length">
      <ion-list-header>
        <ion-label>Found devices</ion-label>
      </ion-list-header>
      <ion-item v-for="d in visibleDevices" :key="d.deviceId" button @click="pick(d)">
        <ion-label>
          <h3>{{ d.name || 'Unnamed' }}</h3>
          <p>{{ d.deviceId }}</p>
        </ion-label>
      </ion-item>
    </ion-list>
    <p v-else-if="found.length && !showAllDevices" class="cal-hint">
      No L-plate devices found yet.
    </p>
    <!-- L-plate controllers advertise as "Lplate-…"; hide everything else behind a link. -->
    <p v-if="!showAllDevices && otherCount" class="show-more">
      <a @click="showAllDevices = true">Show {{ otherCount }} other device{{ otherCount === 1 ? '' : 's' }}</a>
    </p>
    <p v-else-if="showAllDevices && otherCount" class="show-more">
      <a @click="showAllDevices = false">Show only L-plates</a>
    </p>

    <!-- Test the L-plates: connect to the master and toggle the servos. -->
    <ion-list-header class="ion-margin-top">
      <ion-label>Test L-plates</ion-label>
    </ion-list-header>
    <ion-item lines="none">
      <ion-label>{{ plateStatus }}</ion-label>
    </ion-item>
    <ion-button expand="block" fill="outline" :disabled="plateBusy" @click="sendPlates(0)">
      Plates → L
    </ion-button>
    <ion-button expand="block" fill="outline" :disabled="plateBusy" @click="sendPlates(1)">
      Plates → Center (off)
    </ion-button>
    <ion-button expand="block" fill="outline" :disabled="plateBusy" @click="sendPlates(2)">
      Plates → P
    </ion-button>

    <!-- Calibrate each plate's servo travel (just shy of its mechanical stops). -->
    <ion-list-header class="ion-margin-top">
      <ion-label>Calibrate plates</ion-label>
    </ion-list-header>
    <ion-button expand="block" fill="outline" :disabled="plateBusy" @click="loadEdges">
      {{ edges.length ? 'Refresh plates' : 'Connect & load plates' }}
    </ion-button>
    <p v-if="edgesMsg" class="cal-hint">{{ edgesMsg }}</p>

    <template v-for="e in edges" :key="e.i">
      <ion-item lines="full">
        <ion-label>
          <h3>Plate #{{ e.i }}</h3>
          <p>{{ e.mac }} · currently {{ plateName(e.cur) }}</p>
        </ion-label>
        <ion-button slot="end" size="small" fill="outline"
                    :color="calIdx === e.i ? 'success' : 'medium'"
                    @click="calIdx === e.i ? endCal() : startCal(e.i)">
          {{ calIdx === e.i ? 'Close' : 'Calibrate' }}
        </ion-button>
      </ion-item>
      <div v-if="calIdx === e.i" class="cal">
        <p class="cal-hint">
          Drag to move this plate, stopping just <i>before</i> it grinds on each stop.
          Set the L, Center and P positions, then tap Close. Saved on the board.
        </p>
        <ion-range :min="500" :max="2500" :step="25" :value="calUs" @ionChange="onCalRange">
          <ion-label slot="start">500</ion-label>
          <ion-label slot="end">2500</ion-label>
        </ion-range>
        <div class="cal-row"><span>Pulse</span><b>{{ calUs }} µs</b></div>
        <div class="calbtns">
          <ion-button size="small" fill="outline" @click="nudge(-25)">−25</ion-button>
          <ion-button size="small" fill="outline" @click="nudge(25)">+25</ion-button>
          <ion-button size="small" color="primary" @click="saveCal(1)">Set L</ion-button>
          <ion-button size="small" color="primary" @click="saveCal(4)">Set Center</ion-button>
          <ion-button size="small" color="primary" @click="saveCal(2)">Set P</ion-button>
        </div>
      </div>
    </template>

    </template>

    <ion-button
      expand="block"
      class="ion-margin-top"
      @click="save"
    >
      Save
    </ion-button>
    <!-- keeps the Save button reachable while the keyboard is open -->
    <div :style="{ height: kbPad + 'px' }"></div>
  </ion-content>
</template>

<script setup lang="ts">
import { ref, computed, onMounted, onUnmounted } from 'vue'
import {
  modalController,
  alertController,
  IonHeader,
  IonToolbar,
  IonTitle,
  IonButtons,
  IonButton,
  IonContent,
  IonInput,
  IonList,
  IonListHeader,
  IonItem,
  IonLabel,
  IonCheckbox,
  IonRange,
} from '@ionic/vue'
import { Capacitor, type PluginListenerHandle } from '@capacitor/core'
import { Keyboard } from '@capacitor/keyboard'
import { carsStore, type Car } from './classes/cars'
import { plateLink, type PlateEdge } from './classes/plates'

type Found = { deviceId: string; name?: string }

const props = defineProps<{ car: Car | null }>()

const form = ref({
  id: props.car?.id,
  nickname: props.car?.nickname ?? '',
  plate: props.car?.plate ?? '',
  ble_device_name: props.car?.ble_device_name ?? '',
})

const noPlates = ref(false)

// pad the content by the keyboard height so Save stays scrollable into view
const kbPad = ref(0)
const kbSubs: PluginListenerHandle[] = []
onMounted(async () => {
  if (!Capacitor.isNativePlatform()) return
  kbSubs.push(await Keyboard.addListener('keyboardWillShow', i => { kbPad.value = i.keyboardHeight }))
  kbSubs.push(await Keyboard.addListener('keyboardWillHide', () => { kbPad.value = 0 }))
})

const found = ref<Found[]>([])
const scanning = ref(false)

// L-plate controllers advertise as "Lplate-…" (also accept "Lf…" names). By
// default only show those; the rest are hidden behind a "Show more" link so the
// list isn't a wall of random BLE gear.
const showAllDevices = ref(false)
const isLP = (d: Found) => {
  const n = (d.name ?? '').toUpperCase()
  return n.startsWith('LPLATE-') || n.startsWith('LF')
}
const lpDevices = computed(() => found.value.filter(isLP))
const otherCount = computed(() => found.value.length - lpDevices.value.length)
const visibleDevices = computed(() => showAllDevices.value ? found.value : lpDevices.value)

// ── L-plate test ────────────────────────────────────────────────────────────
// Reuses the shared plateLink (src/views/classes/plates.ts). On demand it
// connects to THIS car's master (by its saved device name), toggles, and the
// link is dropped when the modal closes.
const plateStatus = plateLink.status
const plateBusy = ref(false)

// The car as currently edited (may be unsaved), so we connect to its device.
function currentCar(): Car {
  return {
    id: form.value.id ?? -1,
    nickname: form.value.nickname,
    plate: form.value.plate || null,
    ble_device_name: form.value.ble_device_name || null,
    ble_service_uuid: null,
    has_pairing_secret: false,
  } as Car
}

// 0 = L, 1 = Center (off), 2 = P
const plateName = (n: number) => n === 0 ? 'L' : n === 2 ? 'P' : 'Center'
async function sendPlates(state: 0 | 1 | 2) {
  if (plateBusy.value) return
  plateBusy.value = true
  try {
    if (!plateLink.connected.value) await plateLink.connect(currentCar())
    await plateLink.setPlates(state)
  } catch (e) {
    console.error('plate test failed', e)
  } finally {
    plateBusy.value = false
  }
}

// ── Plate servo calibration ───────────────────────────────────────────────────
// Lists this car's paired plates and lets you jog each servo to set its safe
// end-points (saved on the board). Reuses the same live BLE link as the test.
const edges = ref<PlateEdge[]>([])
const edgesMsg = ref('')
const calIdx = ref<number | null>(null)
const calUs = ref(1500)

// Connect (if needed) and read which plates are paired to this car's master.
async function loadEdges() {
  if (plateBusy.value) return
  if (!form.value.ble_device_name) { edgesMsg.value = "Scan and pick this car's device first."; return }
  plateBusy.value = true
  edgesMsg.value = ''
  try {
    if (!plateLink.connected.value) await plateLink.connect(currentCar())
    const s = await plateLink.readStatus()
    edges.value = s.e ?? []
    if (!edges.value.length) edgesMsg.value = 'No plates paired to this car yet.'
  } catch (e) {
    edgesMsg.value = 'could not load plates: ' + e
  } finally {
    plateBusy.value = false
  }
}

const startCal = async (i: number) => {
  calIdx.value = i
  calUs.value = 1500
  try { await plateLink.calibrate(i, 0, calUs.value) }
  catch (e) { edgesMsg.value = 'cal failed: ' + e }
}
const jog = async () => {
  if (calIdx.value === null) return
  try { await plateLink.calibrate(calIdx.value, 0, calUs.value) }
  catch (e) { edgesMsg.value = 'jog failed: ' + e }
}
const onCalRange = async (ev: CustomEvent) => {
  calUs.value = Number((ev.detail as { value: number }).value)
  await jog()
}
const nudge = async (d: number) => {
  calUs.value = Math.max(500, Math.min(2500, calUs.value + d))
  await jog()
}
// action 1 = save as L, 2 = save as P, 4 = save as Center (persisted on the edge).
const saveCal = async (action: 1 | 2 | 4) => {
  if (calIdx.value === null) return
  const label = action === 1 ? 'L' : action === 2 ? 'P' : 'Center'
  try {
    await plateLink.calibrate(calIdx.value, action, calUs.value)
    edgesMsg.value = label + ' set to ' + calUs.value + 'µs'
  } catch (e) { edgesMsg.value = 'save failed: ' + e }
}
const endCal = async () => {
  const i = calIdx.value
  calIdx.value = null
  if (i === null) return
  try { await plateLink.calibrate(i, 3) } catch { /* servo also auto-powers-off */ }
}

// Drop the link when the modal closes.
onUnmounted(() => { calIdx.value = null; plateLink.disconnect(); kbSubs.forEach(s => s.remove()) })

const scan = async () => {
  scanning.value = true
  showAllDevices.value = false
  found.value = []
  try {
    const { BleClient } = await import('@capacitor-community/bluetooth-le')
    await BleClient.initialize()
    await BleClient.requestLEScan({}, r => {
      if (!found.value.find(x => x.deviceId === r.device.deviceId)) {
        found.value.push({ deviceId: r.device.deviceId, name: r.device.name })
      }
    })
    setTimeout(async () => {
      try { await BleClient.stopLEScan() } catch {}
      scanning.value = false
    }, 5000)
  } catch (e) {
    console.error('BLE scan failed', e)
    scanning.value = false
  }
}

const pick = async (d: Found) => {
  form.value.ble_device_name = d.name || d.deviceId
  found.value = []
  // stop the running scan too, or its callback keeps re-adding devices and the
  // list pops back up. it stays hidden until Scan is tapped again.
  scanning.value = false
  try {
    const { BleClient } = await import('@capacitor-community/bluetooth-le')
    await BleClient.stopLEScan()
  } catch { /* nothing to stop */ }
}

const dismiss = (role: string, data?: any) =>
  modalController.dismiss(data, role)

const del = async () => {
  if (!Capacitor.isNativePlatform()) {
    alert("sorry you cant delete cars you need to be on a phone")
    return
  }
  console.log('del tapped, id=', form.value.id)
  if (!form.value.id) return
  const confirm = await alertController.create({
    header: 'Delete car?',
    message: form.value.nickname,
    buttons: [
      { text: 'Cancel', role: 'cancel' },
      { text: 'Delete', role: 'destructive', handler: doDelete },
    ],
  })
  await confirm.present()
}

const doDelete = async () => {
  if (!form.value.id) return
  await carsStore.delete_car(form.value.id)
  dismiss('delete')
}

const save = async () => {
  if (!Capacitor.isNativePlatform()) {
    alert("sorry you cant edit cars you need to be on a phone")
    return
  }
  // no nickname yet: ask for one in a popup instead of silently doing nothing
  if (!form.value.nickname.trim()) {
    const a = await alertController.create({
      header: 'Name your car',
      message: 'Give this car a nickname so you can tell it apart.',
      inputs: [{ name: 'nickname', type: 'text', placeholder: "e.g. Mum's Corolla" }],
      buttons: [
        { text: 'Cancel', role: 'cancel' },
        { text: 'Save', role: 'confirm' },
      ],
    })
    await a.present()
    const { role, data } = await a.onWillDismiss()
    if (role !== 'confirm') return
    const name = (data?.values?.nickname || '').trim()
    if (!name) return
    form.value.nickname = name
  }
  const payload = {
    nickname: form.value.nickname,
    plate: noPlates.value ? null : (form.value.plate || null),
    ble_device_name: form.value.ble_device_name || null,
  }

  if (form.value.id) {
    await carsStore.update_car({ id: form.value.id, ...payload } as Car)
  } else {
    await carsStore.add_car(payload as Car)
  }
  dismiss('save')
}
</script>

<style scoped>
.form-field {
  margin-bottom: 12px;
}
.no-plates-hint {
  font-size: 13px;
  color: var(--ion-color-medium);
  margin: 0 16px 12px;
}
.cal-hint { font-size: 13px; color: var(--ion-color-medium); margin: 6px 16px; }
.cal { padding: 4px 14px 12px; border-bottom: 1px solid var(--ion-color-light); }
.cal-row { display: flex; justify-content: space-between; padding: 2px 0; }
.calbtns { display: flex; gap: 6px; flex-wrap: wrap; margin-top: 6px; }
.show-more { margin: 6px 16px; font-size: 14px; }
.show-more a { color: var(--ion-color-primary); cursor: pointer; text-decoration: underline; }
</style>
