<!-- Generated by AI (Claude) -->
<!-- this is not directly related to progeraming for the web and it is just like a headace with ble so i choce to get ai to genarate -->
<!-- if you would like i am happy to rewrite if i need to -->
<template>
  <ion-header>
    <ion-toolbar>
      <ion-buttons slot="start" v-if="form.id">
        <ion-button color="danger" @click="del">Delete</ion-button>
      </ion-buttons>
      <ion-title>{{ form.id ? 'Edit car' : 'Add car' }}</ion-title>
      <ion-buttons slot="end">
        <ion-button @click="dismiss('cancel')">Cancel</ion-button>
      </ion-buttons>
    </ion-toolbar>
  </ion-header>

  <ion-content class="ion-padding">
    <ion-input
      v-model="form.nickname"
      label="Nickname"
      label-placement="stacked"
    />
    <ion-input
      v-model="form.plate"
      label="Plate"
      label-placement="stacked"
    />
    <ion-input
      v-model="form.ble_device_name"
      label="Device"
      label-placement="stacked"
      readonly
    />

    <ion-button expand="block" fill="outline" @click="scan" :disabled="scanning">
      {{ scanning ? 'Scanning…' : 'Scan for BLE devices' }}
    </ion-button>

    <ion-list v-if="found.length">
      <ion-list-header>
        <ion-label>Found devices</ion-label>
      </ion-list-header>
      <ion-item v-for="d in found" :key="d.deviceId" button @click="pick(d)">
        <ion-label>
          <h3>{{ d.name || 'Unnamed' }}</h3>
          <p>{{ d.deviceId }}</p>
        </ion-label>
      </ion-item>
    </ion-list>

    <!-- Test the L-plates: connect to the master and toggle the servos. -->
    <ion-list-header class="ion-margin-top">
      <ion-label>Test L-plates</ion-label>
    </ion-list-header>
    <ion-item lines="none">
      <ion-label>{{ bleStatus || 'not connected' }}</ion-label>
    </ion-item>
    <ion-button expand="block" fill="outline" :disabled="bleBusy" @click="sendPlates(1)">
      Plates UP
    </ion-button>
    <ion-button expand="block" fill="outline" :disabled="bleBusy" @click="sendPlates(0)">
      Plates DOWN
    </ion-button>

    <ion-button
      expand="block"
      class="ion-margin-top"
      @click="save"
      :disabled="!form.nickname.trim()"
    >
      Save
    </ion-button>
  </ion-content>
</template>

<script setup lang="ts">
import { ref } from 'vue'
import {
  modalController,
  alertController,
  IonHeader,
  IonToolbar,
  IonTitle,
  IonButtons,
  IonButton,
  IonContent,
  IonInput,
  IonList,
  IonListHeader,
  IonItem,
  IonLabel,
} from '@ionic/vue'
import { Capacitor } from '@capacitor/core'
import { carsStore, type Car } from './classes/cars'

type Found = { deviceId: string; name?: string }

const props = defineProps<{ car: Car | null }>()

const form = ref({
  id: props.car?.id,
  nickname: props.car?.nickname ?? '',
  plate: props.car?.plate ?? '',
  ble_device_name: props.car?.ble_device_name ?? '',
})

const found = ref<Found[]>([])
const scanning = ref(false)

// ── L-plate test (BLE) ──────────────────────────────────────────────────────
// These UUIDs must match the master firmware (esp32/src/master/main.cpp).
const PLATE_SERVICE = 'a1b2c3d4-0001-4000-8000-000000000001'
const PLATE_CHAR    = 'a1b2c3d4-0002-4000-8000-000000000002'
const bleStatus = ref('')
const bleBusy = ref(false)
let plateDeviceId = ''   // remembered from a pick or a scan-by-service

// Scan for the master (it advertises PLATE_SERVICE) and return its device id.
async function findMaster(): Promise<string> {
  const { BleClient } = await import('@capacitor-community/bluetooth-le')
  await BleClient.initialize()
  return await new Promise<string>((resolve, reject) => {
    let id = ''
    BleClient.requestLEScan({ services: [PLATE_SERVICE] }, r => {
      if (!id) id = r.device.deviceId
    }).catch(reject)
    setTimeout(async () => {
      try { await BleClient.stopLEScan() } catch {}
      id ? resolve(id) : reject(new Error('L-Plate Master not found'))
    }, 4000)
  })
}

// Write one byte: 1 = plates up, 0 = plates down.
async function sendPlates(state: 0 | 1) {
  if (bleBusy.value) return
  bleBusy.value = true
  try {
    const { BleClient, numbersToDataView } = await import('@capacitor-community/bluetooth-le')
    await BleClient.initialize()
    if (!plateDeviceId) {
      bleStatus.value = 'scanning…'
      plateDeviceId = await findMaster()
    }
    bleStatus.value = 'connecting…'
    await BleClient.connect(plateDeviceId, () => { plateDeviceId = '' })  // clear cache on disconnect
    await BleClient.write(plateDeviceId, PLATE_SERVICE, PLATE_CHAR, numbersToDataView([state]))
    bleStatus.value = state ? 'sent: plates UP' : 'sent: plates DOWN'
  } catch (e: any) {
    plateDeviceId = ''
    bleStatus.value = 'error: ' + (e?.message ?? e)
    console.error('BLE plate test failed', e)
  } finally {
    bleBusy.value = false
  }
}

const scan = async () => {
  scanning.value = true
  found.value = []
  try {
    const { BleClient } = await import('@capacitor-community/bluetooth-le')
    await BleClient.initialize()
    await BleClient.requestLEScan({}, r => {
      if (!found.value.find(x => x.deviceId === r.device.deviceId)) {
        found.value.push({ deviceId: r.device.deviceId, name: r.device.name })
      }
    })
    setTimeout(async () => {
      try { await BleClient.stopLEScan() } catch {}
      scanning.value = false
    }, 5000)
  } catch (e) {
    console.error('BLE scan failed', e)
    scanning.value = false
  }
}

const pick = (d: Found) => {
  form.value.ble_device_name = d.name || d.deviceId
  plateDeviceId = d.deviceId   // reuse for the test buttons, no re-scan needed
  found.value = []
}

const dismiss = (role: string, data?: any) =>
  modalController.dismiss(data, role)

const del = async () => {
  if (!Capacitor.isNativePlatform()) {
    alert("sorry you cant delete cars you need to be on a phone")
    return
  }
  console.log('del tapped, id=', form.value.id)
  if (!form.value.id) return
  const confirm = await alertController.create({
    header: 'Delete car?',
    message: form.value.nickname,
    buttons: [
      { text: 'Cancel', role: 'cancel' },
      { text: 'Delete', role: 'destructive', handler: doDelete },
    ],
  })
  await confirm.present()
}

const doDelete = async () => {
  if (!form.value.id) return
  await carsStore.delete_car(form.value.id)
  dismiss('delete')
}

const save = async () => {
  if (!Capacitor.isNativePlatform()) {
    alert("sorry you cant edit cars you need to be on a phone")
    return
  }
  const payload = {
    nickname: form.value.nickname,
    plate: form.value.plate || null,
    ble_device_name: form.value.ble_device_name || null,
  }

  if (form.value.id) {
    await carsStore.update_car({ id: form.value.id, ...payload } as Car)
  } else {
    await carsStore.add_car(payload as Car)
  }
  dismiss('save')
}
</script>
