[env:esp32c3]
platform = espressif32
board = dfrobot_beetle_esp32c3
framework = arduino
lib_extra_dirs = ~/Documents/Arduino/libraries

; Upload settings
upload_speed = 1500000
monitor_speed = 115200

lib_deps =
  ArduinoJson
  adafruit/Adafruit GPS Library@^1.7.5