<!-- Generated by AI (Claude) -->
<!-- this is not directly related to progeraming for the web and it is just like a headace with ble so i choce to get ai to genarate -->
<!-- if you would like i am happy to rewrite if i need to -->
<template>
  <ion-header>
    <ion-toolbar>
      <ion-buttons slot="start" v-if="form.id">
        <ion-button color="danger" @click="del">Delete</ion-button>
      </ion-buttons>
      <ion-title>{{ form.id ? 'Edit car' : 'Add car' }}</ion-title>
      <ion-buttons slot="end">
        <ion-button @click="dismiss('cancel')">Cancel</ion-button>
      </ion-buttons>
    </ion-toolbar>
  </ion-header>

  <ion-content class="ion-padding">
    <ion-input
      v-model="form.nickname"
      label="Nickname"
      label-placement="stacked"
    />
    <ion-input
      v-model="form.plate"
      label="Plate"
      label-placement="stacked"
    />
    <ion-input
      v-model="form.ble_device_name"
      label="Device"
      label-placement="stacked"
      readonly
    />

    <ion-button expand="block" fill="outline" @click="scan" :disabled="scanning">
      {{ scanning ? 'Scanning…' : 'Scan for BLE devices' }}
    </ion-button>

    <ion-list v-if="found.length">
      <ion-list-header>
        <ion-label>Found devices</ion-label>
      </ion-list-header>
      <ion-item v-for="d in found" :key="d.deviceId" button @click="pick(d)">
        <ion-label>
          <h3>{{ d.name || 'Unnamed' }}</h3>
          <p>{{ d.deviceId }}</p>
        </ion-label>
      </ion-item>
    </ion-list>

    <ion-button
      expand="block"
      class="ion-margin-top"
      @click="save"
      :disabled="!form.nickname.trim()"
    >
      Save
    </ion-button>
  </ion-content>
</template>

<script setup lang="ts">
import { ref } from 'vue'
import {
  modalController,
  alertController,
  IonHeader,
  IonToolbar,
  IonTitle,
  IonButtons,
  IonButton,
  IonContent,
  IonInput,
  IonList,
  IonListHeader,
  IonItem,
  IonLabel,
} from '@ionic/vue'
import { Capacitor } from '@capacitor/core'
import { carsStore, type Car } from './classes/cars'

type Found = { deviceId: string; name?: string }

const props = defineProps<{ car: Car | null }>()

const form = ref({
  id: props.car?.id,
  nickname: props.car?.nickname ?? '',
  plate: props.car?.plate ?? '',
  ble_device_name: props.car?.ble_device_name ?? '',
})

const found = ref<Found[]>([])
const scanning = ref(false)

const scan = async () => {
  scanning.value = true
  found.value = []
  try {
    const { BleClient } = await import('@capacitor-community/bluetooth-le')
    await BleClient.initialize()
    await BleClient.requestLEScan({}, r => {
      if (!found.value.find(x => x.deviceId === r.device.deviceId)) {
        found.value.push({ deviceId: r.device.deviceId, name: r.device.name })
      }
    })
    setTimeout(async () => {
      try { await BleClient.stopLEScan() } catch {}
      scanning.value = false
    }, 5000)
  } catch (e) {
    console.error('BLE scan failed', e)
    scanning.value = false
  }
}

const pick = (d: Found) => {
  form.value.ble_device_name = d.name || d.deviceId
  found.value = []
}

const dismiss = (role: string, data?: any) =>
  modalController.dismiss(data, role)

const del = async () => {
  if (!Capacitor.isNativePlatform()) {
    alert("sorry you cant delete cars you need to be on a phone")
    return
  }
  console.log('del tapped, id=', form.value.id)
  if (!form.value.id) return
  const confirm = await alertController.create({
    header: 'Delete car?',
    message: form.value.nickname,
    buttons: [
      { text: 'Cancel', role: 'cancel' },
      { text: 'Delete', role: 'destructive', handler: doDelete },
    ],
  })
  await confirm.present()
}

const doDelete = async () => {
  if (!form.value.id) return
  await carsStore.delete_car(form.value.id)
  dismiss('delete')
}

const save = async () => {
  if (!Capacitor.isNativePlatform()) {
    alert("sorry you cant edit cars you need to be on a phone")
    return
  }
  const payload = {
    nickname: form.value.nickname,
    plate: form.value.plate || null,
    ble_device_name: form.value.ble_device_name || null,
  }

  if (form.value.id) {
    await carsStore.update_car({ id: form.value.id, ...payload } as Car)
  } else {
    await carsStore.add_car(payload as Car)
  }
  dismiss('save')
}
</script>
