<!-- Generated by AI (Claude) -->
<!-- this is not directly related to progeraming for the web and it is just like a headace with ble so i choce to get ai to genarate -->
<!-- if you would like i am happy to rewrite if i need to -->
<template>
  <ion-header>
    <ion-toolbar>
      <ion-title>{{ form.id ? 'Edit car' : 'Add car' }}</ion-title>
      <ion-buttons slot="end">
        <ion-button @click="dismiss('cancel')">Cancel</ion-button>
      </ion-buttons>
    </ion-toolbar>
  </ion-header>

  <ion-content class="ion-padding">
    <ion-input
      v-model="form.nickname"
      label="Nickname"
      label-placement="stacked"
    />
    <ion-input
      v-model="form.plate"
      label="Plate"
      label-placement="stacked"
    />
    <ion-input
      v-model="form.ble_device_name"
      label="Device"
      label-placement="stacked"
      readonly
    />

    <ion-button expand="block" fill="outline" @click="scan" :disabled="scanning">
      {{ scanning ? 'Scanning…' : 'Scan for BLE devices' }}
    </ion-button>

    <ion-list v-if="found.length">
      <ion-list-header>
        <ion-label>Found devices</ion-label>
      </ion-list-header>
      <ion-item v-for="d in found" :key="d.deviceId" button @click="pick(d)">
        <ion-label>
          <h3>{{ d.name || 'Unnamed' }}</h3>
          <p>{{ d.deviceId }}</p>
        </ion-label>
      </ion-item>
    </ion-list>

    <ion-button
      expand="block"
      class="ion-margin-top"
      @click="save"
      :disabled="!form.nickname.trim()"
    >
      Save
    </ion-button>
  </ion-content>
</template>

<script setup lang="ts">
import { ref } from 'vue'
import {
  modalController,
  IonHeader,
  IonToolbar,
  IonTitle,
  IonButtons,
  IonButton,
  IonContent,
  IonInput,
  IonList,
  IonListHeader,
  IonItem,
  IonLabel,
} from '@ionic/vue'
import { Preferences } from '@capacitor/preferences'
import { CapacitorHttp } from '@capacitor/core'

type Car = {
  id?: number
  nickname: string
  plate: string | null
  ble_device_name: string | null
}

type Found = { deviceId: string; name?: string }

const props = defineProps<{ car: Car | null }>()
const API_URL = import.meta.env.VITE_API_URL

const form = ref({
  id: props.car?.id,
  nickname: props.car?.nickname ?? '',
  plate: props.car?.plate ?? '',
  ble_device_name: props.car?.ble_device_name ?? '',
})

const found = ref<Found[]>([])
const scanning = ref(false)

const scan = async () => {
  scanning.value = true
  found.value = []
  try {
    const { BleClient } = await import('@capacitor-community/bluetooth-le')
    await BleClient.initialize()
    await BleClient.requestLEScan({}, r => {
      if (!found.value.find(x => x.deviceId === r.device.deviceId)) {
        found.value.push({ deviceId: r.device.deviceId, name: r.device.name })
      }
    })
    setTimeout(async () => {
      try { await BleClient.stopLEScan() } catch {}
      scanning.value = false
    }, 5000)
  } catch (e) {
    console.error('BLE scan failed', e)
    scanning.value = false
  }
}

const pick = (d: Found) => {
  form.value.ble_device_name = d.name || d.deviceId
  found.value = []
}

const dismiss = (role: string, data?: any) =>
  modalController.dismiss(data, role)

const save = async () => {
  const { value: token } = await Preferences.get({ key: 'auth_token' })
  const headers = {
    'Content-Type': 'application/json',
    Authorization: `Bearer ${token}`,
  }

  const isEdit = !!form.value.id
  const url = isEdit
    ? `${API_URL}/api/cars/${form.value.id}`
    : `${API_URL}/api/cars`

  const res = isEdit
    ? await CapacitorHttp.patch({ url, headers, data: form.value })
    : await CapacitorHttp.post({ url, headers, data: form.value })

  if (res.status === 200) dismiss('save', res.data)
  else console.error('save failed', res.status, res.data)
}
</script>
